### PR TITLE
Dynamically activating menu items

### PR DESCRIPTION
**Pull request by prabushitha**
Fix for the issue #1

### CODE REVIEW

**Comment by vishalsanghai** [comment]
I am afraid it's not working for me. Are you sure it's working for you?

The active state is only there for home menuBar item throughout and it's not changing to other sections.

**Comment by prabushitha** [comment]
@vishalsanghai  It's working very well. May be try cleaning the cache. If not worked, can you post here the console (screenshot)?

**Comment by vishalsanghai** [comment]
one
two
The active tabs work on clicking that particular tab, but it doesn't change on scrolling to a different section. See the screenshots, the home tab is active in the first screen which is fine, but on scrolling to the second section it is still active, whereas now the product tab should have been active.
To implement this part you can refer to the code from around 950-975 which is commented, you will have to use cursorPosition and section top and bottom position to know when to show which tab as active.

**Comment by vishalsanghai** [comment]
Thanks @prabushitha. It's working absolutely fine! You can look at other issues in this project or open new issues if you want to.

**Pull request merged**
